name: 'Terraform Apply'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v3

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: 'Configure AWS CLI'
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-east-1
        if [ ! -z "${{ secrets.AWS_SESSION_TOKEN }}" ]; then
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
        fi

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Validate'
      run: terraform validate

    - name: 'Terraform Plan'
      run: terraform plan -out=tfplan

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve tfplan

    - name: 'Upload Terraform State'
      uses: actions/upload-artifact@v3
      with:
        name: terraform-state
        path: |
          terraform.tfstate
          .terraform/
